name: Code Quality Checks

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  code_scan:
    name: Code Scanner
    runs-on: ubuntu-latest

    steps:
      - name: PR Title Checker
        uses: thehanimo/pr-title-checker@v1.4.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: .github/config/pr_title_checker_config.json
